#!/usr/bin/env bash
set -uo pipefail

# Installs the kit's minimal shell aliases (`hr`, `house-rules`) plus a
# PROCESS_KIT env var into the user's shell rc file. Uses the
# owned-file pattern: writes ~/.house-rules-aliases.sh (overwritten on every
# run, safe to regenerate) and adds a single marker-delimited source line
# to ~/.zshrc / ~/.bashrc. This avoids marker-block editing on the shell
# rc file for anything other than the one source line.
#
# Non-interactive by design — safe for agent-driven machine setup.
#
# Usage:
#   ./scripts/install-aliases.sh                # Install / update (auto-detect shell)
#   ./scripts/install-aliases.sh --shell zsh    # Force shell choice
#   ./scripts/install-aliases.sh --check        # Report status, no writes
#   ./scripts/install-aliases.sh --uninstall    # Remove aliases file + rc source line
#   ./scripts/install-aliases.sh --help

KIT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ALIASES_FILE="$HOME/.house-rules-aliases.sh"
# Marker prefix is "house-rules:" (final kit name, decision 0001 A1).
# Recognition of the predecessor playbook's legacy marker prefix was
# sunset 2026-08-06 (process-kit-26b) after a field sweep showed zero
# old-marker rc blocks remaining.
SOURCE_BEGIN="# BEGIN house-rules:aliases"
SOURCE_END="# END house-rules:aliases"
MODE="install"
SHELL_OVERRIDE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)     MODE="check"; shift ;;
    --uninstall) MODE="uninstall"; shift ;;
    --shell)     SHELL_OVERRIDE="$2"; shift 2 ;;
    -h|--help)
      cat <<'EOF'
Installs minimal house-rules shell aliases.

Usage: install-aliases.sh [options]

Modes:
  (default)     Install or update aliases. Detects zsh/bash/fish via $SHELL.
  --check       Report whether aliases are installed and current (exit 1 if not).
  --uninstall   Remove the rc source line and delete ~/.house-rules-aliases.sh.
  --shell ARG   Override shell detection (zsh|bash|fish).
  --help        Show this help.

Installed aliases:
  hr                   The house-rules dispatcher (init | doctor | sync)
  house-rules          Same dispatcher, full name
  PROCESS_KIT          Exported env var pointing at the kit clone

The aliases source ~/.house-rules-aliases.sh, which is overwritten on each
install. Do not edit that file by hand. Re-run this installer to update.

Non-interactive by design — safe for agent-driven machine setup.
EOF
      exit 0
      ;;
    *) echo "Unknown option: $1 (use --help)" >&2; exit 1 ;;
  esac
done

# --- Shell detection ---

detect_shell() {
  local name=""
  if [ -n "$SHELL_OVERRIDE" ]; then
    name="$SHELL_OVERRIDE"
  elif [ -n "${SHELL:-}" ]; then
    name="$(basename "$SHELL")"
  fi
  case "$name" in
    zsh)  echo "zsh" ;;
    bash) echo "bash" ;;
    fish) echo "fish" ;;
    *)    echo "unsupported" ;;
  esac
}

rc_file_for() {
  case "$1" in
    zsh)  echo "$HOME/.zshrc" ;;
    bash)
      if [ -f "$HOME/.bashrc" ]; then
        echo "$HOME/.bashrc"
      else
        echo "$HOME/.bash_profile"
      fi
      ;;
    fish) echo "$HOME/.config/fish/config.fish" ;;
    *) echo "" ;;
  esac
}

# --- Aliases file content ---

render_aliases_file() {
  cat <<ALIASES
# house-rules aliases (managed by install-aliases.sh)
#
# This file is regenerated by install-aliases.sh. Do not edit by hand —
# changes will be lost on the next install. To customize, edit your own
# shell rc and source this file earlier so your aliases take precedence.
#
# Re-run installer:
#   bash "\${PROCESS_KIT:-\$HOME/process-kit}/scripts/install-aliases.sh"

export PROCESS_KIT="\${PROCESS_KIT:-$KIT_ROOT}"

# hr / house-rules: the kit dispatcher (init | doctor | sync)
alias hr='bash "\$PROCESS_KIT/scripts/house-rules"'
alias house-rules='bash "\$PROCESS_KIT/scripts/house-rules"'
ALIASES
}

# Writer return codes (shared by the writers below): 0 = written, 1 = I/O
# failure (mktemp/write/mv — callers must fail loud, process-kit-e71),
# 2 = malformed markers (deliberate warn-and-skip, file untouched — the
# process-kit-0em guard contract).
write_aliases_file() {
  local tmp
  tmp="$(mktemp "${ALIASES_FILE}.tmp.XXXXXX")" || return 1
  render_aliases_file > "$tmp" || { rm -f "$tmp"; return 1; }
  mv "$tmp" "$ALIASES_FILE" || { rm -f "$tmp"; return 1; }
}

aliases_file_is_current() {
  [ -f "$ALIASES_FILE" ] || return 1
  local want have
  want="$(render_aliases_file)"
  have="$(cat "$ALIASES_FILE")"
  [ "$want" = "$have" ]
}

# --- RC file block (single source line, marker-delimited so --uninstall works) ---

rc_block() {
  cat <<BLOCK
$SOURCE_BEGIN
[ -f "\$HOME/.house-rules-aliases.sh" ] && . "\$HOME/.house-rules-aliases.sh"
$SOURCE_END
BLOCK
}

rc_has_block() {
  local rc="$1"
  [ -f "$rc" ] || return 1
  grep -qF "$SOURCE_BEGIN" "$rc"
}

# Content check: the block's body can change across kit versions (it did at
# the v0.3.0 dispatcher cut, when the sourced filename changed), so presence
# alone is not "installed" — a present-but-stale block gets refreshed.
rc_block_is_current() {
  local rc="$1"
  rc_has_block "$rc" || return 1
  local want have
  want="$(rc_block)"
  have="$(awk -v b="$SOURCE_BEGIN" -v e="$SOURCE_END" \
    '$0==b{f=1} f{print} $0==e{f=0}' "$rc")"
  [ "$have" = "$want" ]
}

rc_append_block() {
  local rc="$1"
  mkdir -p "$(dirname "$rc")" || return 1
  # Atomic write: stage the new content (existing rc + spacer + block) to
  # a temp file in the same directory, then mv. A non-atomic group
  # append (`{ ... } >> "$rc"`) is exposed to OOM kills and SIGKILL
  # mid-write — the rc would be left with a syntactically broken shell
  # block (breaking every new terminal) and the orphan BEGIN marker
  # would make `rc_has_block` falsely report "already installed" on
  # re-run, bypassing repair.
  local tmp
  tmp="$(mktemp "${rc}.tmp.XXXXXX")" || return 1
  {
    if [ -f "$rc" ]; then
      cat "$rc"
      # Ensure trailing newline before appending
      [ -n "$(tail -c1 "$rc" 2>/dev/null)" ] && printf '\n'
      printf '\n'
    fi
    rc_block
    printf '\n'
  } > "$tmp" || { rm -f "$tmp"; return 1; }
  mv "$tmp" "$rc" || { rm -f "$tmp"; return 1; }
}

# One scanner for both rewrites: strips every managed block; with `emit`,
# re-emits the current block at the first BEGIN — in place, because block
# position in the rc is load-bearing (source-order precedence). Used by
# uninstall (strip) and by the content refresh (emit) when a present block
# body is stale.
rc_rewrite_block() {
  local rc="$1" emit="${2:-}"
  local tmp
  tmp="$(mktemp "${rc}.tmp.XXXXXX")" || return 1
  local in_block=0 consumed=0 malformed=0
  while IFS= read -r line || [ -n "$line" ]; do
    if [ $in_block -eq 0 ]; then
      if [ "$line" = "$SOURCE_BEGIN" ]; then
        in_block=1
        if [ -n "$emit" ] && [ $consumed -eq 0 ]; then
          rc_block
        fi
        consumed=1
        continue
      fi
      # Orphan END is malformed grammar — refuse rather than copy it
      # through and claim a clean rewrite.
      if [ "$line" = "$SOURCE_END" ]; then
        malformed=1
        break
      fi
      printf '%s\n' "$line"
      continue
    fi
    # in_block=1: only the exact END closes cleanly. Any other rc
    # house-rules marker (nested BEGIN, near-miss END with trailing
    # whitespace) means the scan would discard user bytes — refuse.
    if [ "$line" = "$SOURCE_END" ]; then
      in_block=0
      continue
    fi
    case "$line" in
      '# BEGIN house-rules:'*|'# END house-rules:'*)
        malformed=1
        break
        ;;
    esac
    continue
  done < "$rc" > "$tmp"
  # Refuse the rewrite when the marker scan went wrong: an unpaired BEGIN
  # (in_block still open at EOF), a nested/near-miss marker, an orphan
  # END, or a scan that consumed no BEGIN (e.g. CRLF markers).
  if [ $in_block -eq 1 ] || [ $consumed -eq 0 ] || [ $malformed -eq 1 ]; then
    rm -f "$tmp"
    echo "⚠ $rc: alias block markers are malformed (unpaired/nested BEGIN/END or not line-exact, e.g. CRLF); file left untouched — repair the marker lines manually" >&2
    return 2
  fi
  mv "$tmp" "$rc" || { rm -f "$tmp"; return 1; }
}

rc_remove_block() {
  local rc="$1"
  [ -f "$rc" ] || return 0
  rc_has_block "$rc" || return 0
  rc_rewrite_block "$rc"
}

# --- Dispatch ---

shell_kind="$(detect_shell)"
rc_file="$(rc_file_for "$shell_kind")"

if [ "$shell_kind" = "fish" ]; then
  cat >&2 <<'FISH'
Fish shell isn't supported yet by install-aliases.sh.

Workaround — paste the following into your ~/.config/fish/config.fish:

  set -x PROCESS_KIT "$HOME/process-kit"
  alias hr="bash \"$PROCESS_KIT/scripts/house-rules\""

Or use the scripts directly. File an issue if proper fish support would help.
FISH
  exit 1
fi

if [ "$shell_kind" = "unsupported" ]; then
  echo "ERROR: could not detect a supported shell (zsh or bash)." >&2
  echo "  Override with --shell zsh|bash|fish, or export SHELL before re-running." >&2
  exit 1
fi

case "$MODE" in
  check)
    missing=0
    if ! aliases_file_is_current; then
      echo "✗ $ALIASES_FILE missing or out of date"
      missing=1
    else
      echo "✓ $ALIASES_FILE installed and current"
    fi
    if ! rc_has_block "$rc_file"; then
      echo "✗ Source line not present in $rc_file"
      missing=1
    elif ! rc_block_is_current "$rc_file"; then
      echo "✗ Source block in $rc_file is out of date (re-run installer to refresh)"
      missing=1
    else
      echo "✓ Source line present in $rc_file"
    fi
    if [ $missing -eq 1 ]; then
      echo ""
      echo "  Fix: bash $(cd "$(dirname "$0")" && pwd)/install-aliases.sh"
      exit 1
    fi
    exit 0
    ;;

  uninstall)
    changed=0
    failed=0
    refused=0
    if [ -f "$ALIASES_FILE" ]; then
      if rm -f "$ALIASES_FILE"; then
        echo "✓ Removed $ALIASES_FILE"
        changed=1
      else
        echo "✗ Failed to remove $ALIASES_FILE (check permissions)" >&2
        failed=$((failed + 1))
      fi
    fi
    if rc_has_block "$rc_file"; then
      rc_remove_block "$rc_file"
      case $? in
        0)
          echo "✓ Removed source line from $rc_file"
          changed=1
          ;;
        2)
          # Malformed markers: warned on stderr, file untouched (0em
          # contract) — but the block is still there, so this uninstall
          # did not finish; report and exit nonzero, don't claim success.
          refused=$((refused + 1))
          ;;
        *)
          echo "✗ Failed to rewrite $rc_file removing the source line (write error — check permissions)" >&2
          failed=$((failed + 1))
          ;;
      esac
    fi
    if [ $changed -eq 0 ] && [ $failed -eq 0 ] && [ $refused -eq 0 ]; then
      echo "  Nothing to remove (not installed)."
    elif [ $changed -eq 1 ]; then
      echo ""
      echo "Restart your shell or run: source $rc_file"
    fi
    if [ $refused -gt 0 ]; then
      echo "⚠ The source block in $rc_file was NOT removed (malformed markers — see warning above; repair the marker lines and re-run)" >&2
    fi
    [ $((failed + refused)) -gt 0 ] && exit 1
    exit 0
    ;;

  install)
    echo "=== Installing house-rules aliases ($shell_kind) ==="
    echo ""

    failed=0
    refused=0
    if aliases_file_is_current; then
      echo "✓ $ALIASES_FILE is already current"
    elif write_aliases_file; then
      echo "✓ Wrote $ALIASES_FILE"
    else
      echo "✗ Failed to write $ALIASES_FILE (write error — check permissions)" >&2
      failed=$((failed + 1))
    fi

    if rc_block_is_current "$rc_file"; then
      echo "✓ Source line already present in $rc_file"
    elif rc_has_block "$rc_file"; then
      rc_rewrite_block "$rc_file" emit
      case $? in
        0) echo "✓ Refreshed the source block in $rc_file" ;;
        2)
          # Malformed markers: warned on stderr, file untouched (0em
          # contract) — but the rc still sources nothing current, so the
          # aliases are NOT active; report and exit nonzero, matching
          # what --check would say about this exact state.
          refused=$((refused + 1))
          ;;
        *)
          echo "✗ Failed to rewrite the source block in $rc_file (write error — check permissions)" >&2
          failed=$((failed + 1))
          ;;
      esac
    else
      if rc_append_block "$rc_file"; then
        echo "✓ Added source line to $rc_file"
      else
        echo "✗ Failed to append the source line to $rc_file (write error — check permissions)" >&2
        failed=$((failed + 1))
      fi
    fi

    echo ""
    if [ $((failed + refused)) -eq 0 ]; then
      echo "=== Done ==="
      echo ""
      echo "Activate now: source \"$rc_file\"   (or open a new terminal)"
      echo ""
      echo "Installed aliases:"
      echo "  hr             The house-rules dispatcher (init | doctor | sync)"
      echo "  house-rules    Same dispatcher, full name"
      echo "  PROCESS_KIT → $KIT_ROOT"
      echo ""
      echo "Verify: bash $(cd "$(dirname "$0")" && pwd)/install-aliases.sh --check"
      exit 0
    fi
    echo "=== Incomplete ==="
    echo ""
    if [ $refused -gt 0 ]; then
      echo "⚠ The rc source block was NOT refreshed (malformed markers — see warning above); the aliases are not active until the marker lines in $rc_file are repaired and the installer re-run" >&2
    fi
    if [ $failed -gt 0 ]; then
      echo "✗ $failed write failure(s) above — the ✗-marked items were NOT installed" >&2
    fi
    exit 1
    ;;
esac
