#!/usr/bin/env bash
set -uo pipefail

# Installs the playbook's minimal shell aliases (`pbi`, `pbd`) plus a
# PROCESS_KIT env var into the user's shell rc file. Uses the
# owned-file pattern: writes ~/.playbook-aliases.sh (overwritten on every
# run, safe to regenerate) and adds a single marker-delimited source line
# to ~/.zshrc / ~/.bashrc. This avoids marker-block editing on the shell
# rc file for anything other than the one source line.
#
# Non-interactive by design — safe for agent-driven machine setup.
#
# Usage:
#   ./scripts/install-aliases.sh                # Install / update (auto-detect shell)
#   ./scripts/install-aliases.sh --shell zsh    # Force shell choice
#   ./scripts/install-aliases.sh --check        # Report status, no writes
#   ./scripts/install-aliases.sh --uninstall    # Remove aliases file + rc source line
#   ./scripts/install-aliases.sh --help

PLAYBOOK_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ALIASES_FILE="$HOME/.playbook-aliases.sh"
# Marker prefix is "house-rules:" (final kit name, decision 0001 A1). Rc
# files on machines set up by the predecessor playbook carry the legacy
# "ai-dev-playbook:" prefix, so the block scans below recognize BOTH prefixes:
# a legacy block is rewritten in place under the new markers, never
# duplicated. Keep the legacy recognition until no machine still carries an
# old-marker rc block.
SOURCE_BEGIN="# BEGIN house-rules:aliases"
SOURCE_END="# END house-rules:aliases"
LEGACY_SOURCE_BEGIN="# BEGIN ai-dev-playbook:aliases"
LEGACY_SOURCE_END="# END ai-dev-playbook:aliases"
MODE="install"
SHELL_OVERRIDE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)     MODE="check"; shift ;;
    --uninstall) MODE="uninstall"; shift ;;
    --shell)     SHELL_OVERRIDE="$2"; shift 2 ;;
    -h|--help)
      cat <<'EOF'
Installs minimal playbook (process-kit) shell aliases.

Usage: install-aliases.sh [options]

Modes:
  (default)     Install or update aliases. Detects zsh/bash/fish via $SHELL.
  --check       Report whether aliases are installed and current (exit 1 if not).
  --uninstall   Remove the rc source line and delete ~/.playbook-aliases.sh.
  --shell ARG   Override shell detection (zsh|bash|fish).
  --help        Show this help.

Installed aliases:
  pbi                  Bootstrap the current project (playbook-init.sh)
  pbd                  Diagnose the current project (playbook-doctor.sh)
  PROCESS_KIT          Exported env var pointing at the kit clone

The aliases source ~/.playbook-aliases.sh, which is overwritten on each
install. Do not edit that file by hand. Re-run this installer to update.

Non-interactive by design — safe for agent-driven machine setup.
EOF
      exit 0
      ;;
    *) echo "Unknown option: $1 (use --help)" >&2; exit 1 ;;
  esac
done

# --- Shell detection ---

detect_shell() {
  local name=""
  if [ -n "$SHELL_OVERRIDE" ]; then
    name="$SHELL_OVERRIDE"
  elif [ -n "${SHELL:-}" ]; then
    name="$(basename "$SHELL")"
  fi
  case "$name" in
    zsh)  echo "zsh" ;;
    bash) echo "bash" ;;
    fish) echo "fish" ;;
    *)    echo "unsupported" ;;
  esac
}

rc_file_for() {
  case "$1" in
    zsh)  echo "$HOME/.zshrc" ;;
    bash)
      if [ -f "$HOME/.bashrc" ]; then
        echo "$HOME/.bashrc"
      else
        echo "$HOME/.bash_profile"
      fi
      ;;
    fish) echo "$HOME/.config/fish/config.fish" ;;
    *) echo "" ;;
  esac
}

# --- Aliases file content ---

render_aliases_file() {
  cat <<ALIASES
# process-kit aliases (managed by install-aliases.sh)
#
# This file is regenerated by install-aliases.sh. Do not edit by hand —
# changes will be lost on the next install. To customize, edit your own
# shell rc and source this file earlier so your aliases take precedence.
#
# Re-run installer:
#   bash "\${PROCESS_KIT:-\$HOME/process-kit}/scripts/install-aliases.sh"

export PROCESS_KIT="\${PROCESS_KIT:-$PLAYBOOK_ROOT}"

# pbi: bootstrap the current project (interactive or pass --tool)
alias pbi='bash "\$PROCESS_KIT/scripts/playbook-init.sh"'

# pbd: diagnose the current project (human-readable)
alias pbd='bash "\$PROCESS_KIT/scripts/playbook-doctor.sh"'
ALIASES
}

write_aliases_file() {
  local tmp
  tmp="$(mktemp "${ALIASES_FILE}.tmp.XXXXXX")"
  render_aliases_file > "$tmp"
  mv "$tmp" "$ALIASES_FILE"
}

aliases_file_is_current() {
  [ -f "$ALIASES_FILE" ] || return 1
  local want have
  want="$(render_aliases_file)"
  have="$(cat "$ALIASES_FILE")"
  [ "$want" = "$have" ]
}

# --- RC file block (single source line, marker-delimited so --uninstall works) ---

rc_block() {
  cat <<BLOCK
$SOURCE_BEGIN
[ -f "\$HOME/.playbook-aliases.sh" ] && . "\$HOME/.playbook-aliases.sh"
$SOURCE_END
BLOCK
}

rc_has_block() {
  local rc="$1"
  [ -f "$rc" ] || return 1
  grep -qF "$SOURCE_BEGIN" "$rc" || grep -qF "$LEGACY_SOURCE_BEGIN" "$rc"
}

rc_has_legacy_block() {
  local rc="$1"
  [ -f "$rc" ] && grep -qF "$LEGACY_SOURCE_BEGIN" "$rc"
}

rc_append_block() {
  local rc="$1"
  mkdir -p "$(dirname "$rc")"
  # Atomic write: stage the new content (existing rc + spacer + block) to
  # a temp file in the same directory, then mv. A non-atomic group
  # append (`{ ... } >> "$rc"`) is exposed to OOM kills and SIGKILL
  # mid-write — the rc would be left with a syntactically broken shell
  # block (breaking every new terminal) and the orphan BEGIN marker
  # would make `rc_has_block` falsely report "already installed" on
  # re-run, bypassing repair.
  local tmp
  tmp="$(mktemp "${rc}.tmp.XXXXXX")"
  {
    if [ -f "$rc" ]; then
      cat "$rc"
      # Ensure trailing newline before appending
      [ -n "$(tail -c1 "$rc" 2>/dev/null)" ] && printf '\n'
      printf '\n'
    fi
    rc_block
    printf '\n'
  } > "$tmp"
  mv "$tmp" "$rc"
}

rc_remove_block() {
  local rc="$1"
  [ -f "$rc" ] || return 0
  rc_has_block "$rc" || return 0
  local tmp
  tmp="$(mktemp "${rc}.tmp.XXXXXX")"
  local in_block=0
  while IFS= read -r line || [ -n "$line" ]; do
    if [ $in_block -eq 0 ] && { [ "$line" = "$SOURCE_BEGIN" ] || [ "$line" = "$LEGACY_SOURCE_BEGIN" ]; }; then
      in_block=1
      continue
    fi
    if [ $in_block -eq 1 ]; then
      if [ "$line" = "$SOURCE_END" ] || [ "$line" = "$LEGACY_SOURCE_END" ]; then
        in_block=0
      fi
      continue
    fi
    printf '%s\n' "$line"
  done < "$rc" > "$tmp"
  mv "$tmp" "$rc"
}

# Rewrite a legacy-marked block (and any duplicate managed block) in place
# under the current markers — one block out, regardless of what was in.
rc_migrate_block() {
  local rc="$1"
  local tmp
  tmp="$(mktemp "${rc}.tmp.XXXXXX")"
  local in_block=0 emitted=0
  while IFS= read -r line || [ -n "$line" ]; do
    if [ $in_block -eq 0 ] && { [ "$line" = "$SOURCE_BEGIN" ] || [ "$line" = "$LEGACY_SOURCE_BEGIN" ]; }; then
      in_block=1
      if [ $emitted -eq 0 ]; then
        rc_block
        emitted=1
      fi
      continue
    fi
    if [ $in_block -eq 1 ]; then
      if [ "$line" = "$SOURCE_END" ] || [ "$line" = "$LEGACY_SOURCE_END" ]; then
        in_block=0
      fi
      continue
    fi
    printf '%s\n' "$line"
  done < "$rc" > "$tmp"
  mv "$tmp" "$rc"
}

# --- Dispatch ---

shell_kind="$(detect_shell)"
rc_file="$(rc_file_for "$shell_kind")"

if [ "$shell_kind" = "fish" ]; then
  cat >&2 <<'FISH'
Fish shell isn't supported yet by install-aliases.sh.

Workaround — paste the following into your ~/.config/fish/config.fish:

  set -x PROCESS_KIT "$HOME/process-kit"
  alias pbi="bash \"$PROCESS_KIT/scripts/playbook-init.sh\""
  alias pbd="bash \"$PROCESS_KIT/scripts/playbook-doctor.sh\""

Or use the scripts directly. File an issue if proper fish support would help.
FISH
  exit 1
fi

if [ "$shell_kind" = "unsupported" ]; then
  echo "ERROR: could not detect a supported shell (zsh or bash)." >&2
  echo "  Override with --shell zsh|bash|fish, or export SHELL before re-running." >&2
  exit 1
fi

case "$MODE" in
  check)
    missing=0
    if ! aliases_file_is_current; then
      echo "✗ $ALIASES_FILE missing or out of date"
      missing=1
    else
      echo "✓ $ALIASES_FILE installed and current"
    fi
    if ! rc_has_block "$rc_file"; then
      echo "✗ Source line not present in $rc_file"
      missing=1
    elif rc_has_legacy_block "$rc_file"; then
      echo "⚠ Alias block in $rc_file carries legacy ai-dev-playbook markers (out of date — re-run installer to migrate)"
      missing=1
    else
      echo "✓ Source line present in $rc_file"
    fi
    if [ $missing -eq 1 ]; then
      echo ""
      echo "  Fix: bash $(cd "$(dirname "$0")" && pwd)/install-aliases.sh"
      exit 1
    fi
    exit 0
    ;;

  uninstall)
    changed=0
    if [ -f "$ALIASES_FILE" ]; then
      rm -f "$ALIASES_FILE"
      echo "✓ Removed $ALIASES_FILE"
      changed=1
    fi
    if rc_has_block "$rc_file"; then
      rc_remove_block "$rc_file"
      echo "✓ Removed source line from $rc_file"
      changed=1
    fi
    if [ $changed -eq 0 ]; then
      echo "  Nothing to remove (not installed)."
    else
      echo ""
      echo "Restart your shell or run: source $rc_file"
    fi
    exit 0
    ;;

  install)
    echo "=== Installing process-kit aliases ($shell_kind) ==="
    echo ""

    if aliases_file_is_current; then
      echo "✓ $ALIASES_FILE is already current"
    else
      write_aliases_file
      echo "✓ Wrote $ALIASES_FILE"
    fi

    if rc_has_legacy_block "$rc_file"; then
      rc_migrate_block "$rc_file"
      echo "✓ Migrated alias block in $rc_file to house-rules markers"
    elif rc_has_block "$rc_file"; then
      echo "✓ Source line already present in $rc_file"
    else
      rc_append_block "$rc_file"
      echo "✓ Added source line to $rc_file"
    fi

    echo ""
    echo "=== Done ==="
    echo ""
    echo "Activate now: source \"$rc_file\"   (or open a new terminal)"
    echo ""
    echo "Installed aliases:"
    echo "  pbi            Bootstrap the current project"
    echo "  pbd            Diagnose the current project"
    echo "  PROCESS_KIT → $PLAYBOOK_ROOT"
    echo ""
    echo "Verify: bash $(cd "$(dirname "$0")" && pwd)/install-aliases.sh --check"
    exit 0
    ;;
esac
